// Generated by gencpp from file infrared_msgs/IrDetection.msg
// DO NOT EDIT!


#ifndef INFRARED_MSGS_MESSAGE_IRDETECTION_H
#define INFRARED_MSGS_MESSAGE_IRDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace infrared_msgs
{
template <class ContainerAllocator>
struct IrDetection_
{
  typedef IrDetection_<ContainerAllocator> Type;

  IrDetection_()
    : header()
    , emitter_id()
    , distance(0.0)
    , strength(0.0)
    , direction()
    , signal_to_noise(0.0)
    , line_of_sight(false)  {
    }
  IrDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , emitter_id(_alloc)
    , distance(0.0)
    , strength(0.0)
    , direction(_alloc)
    , signal_to_noise(0.0)
    , line_of_sight(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _emitter_id_type;
  _emitter_id_type emitter_id;

   typedef double _distance_type;
  _distance_type distance;

   typedef double _strength_type;
  _strength_type strength;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _direction_type;
  _direction_type direction;

   typedef double _signal_to_noise_type;
  _signal_to_noise_type signal_to_noise;

   typedef uint8_t _line_of_sight_type;
  _line_of_sight_type line_of_sight;





  typedef boost::shared_ptr< ::infrared_msgs::IrDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrared_msgs::IrDetection_<ContainerAllocator> const> ConstPtr;

}; // struct IrDetection_

typedef ::infrared_msgs::IrDetection_<std::allocator<void> > IrDetection;

typedef boost::shared_ptr< ::infrared_msgs::IrDetection > IrDetectionPtr;
typedef boost::shared_ptr< ::infrared_msgs::IrDetection const> IrDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrared_msgs::IrDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrared_msgs::IrDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrared_msgs::IrDetection_<ContainerAllocator1> & lhs, const ::infrared_msgs::IrDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.emitter_id == rhs.emitter_id &&
    lhs.distance == rhs.distance &&
    lhs.strength == rhs.strength &&
    lhs.direction == rhs.direction &&
    lhs.signal_to_noise == rhs.signal_to_noise &&
    lhs.line_of_sight == rhs.line_of_sight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrared_msgs::IrDetection_<ContainerAllocator1> & lhs, const ::infrared_msgs::IrDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrared_msgs::IrDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrared_msgs::IrDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrared_msgs::IrDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrared_msgs::IrDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrared_msgs::IrDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrared_msgs::IrDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrared_msgs::IrDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8765f5c28a65d3ab4e34a4adb77d9b1";
  }

  static const char* value(const ::infrared_msgs::IrDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8765f5c28a65d3aULL;
  static const uint64_t static_value2 = 0xb4e34a4adb77d9b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrared_msgs::IrDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrared_msgs/IrDetection";
  }

  static const char* value(const ::infrared_msgs::IrDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrared_msgs::IrDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string emitter_id\n"
"float64 distance\n"
"float64 strength\n"
"geometry_msgs/Vector3 direction\n"
"float64 signal_to_noise\n"
"bool line_of_sight\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::infrared_msgs::IrDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrared_msgs::IrDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.emitter_id);
      stream.next(m.distance);
      stream.next(m.strength);
      stream.next(m.direction);
      stream.next(m.signal_to_noise);
      stream.next(m.line_of_sight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IrDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrared_msgs::IrDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrared_msgs::IrDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "emitter_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.emitter_id);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "strength: ";
    Printer<double>::stream(s, indent + "  ", v.strength);
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
    s << indent << "signal_to_noise: ";
    Printer<double>::stream(s, indent + "  ", v.signal_to_noise);
    s << indent << "line_of_sight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.line_of_sight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRARED_MSGS_MESSAGE_IRDETECTION_H
