// Generated by gencpp from file infrared_msgs/IrSignal.msg
// DO NOT EDIT!


#ifndef INFRARED_MSGS_MESSAGE_IRSIGNAL_H
#define INFRARED_MSGS_MESSAGE_IRSIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace infrared_msgs
{
template <class ContainerAllocator>
struct IrSignal_
{
  typedef IrSignal_<ContainerAllocator> Type;

  IrSignal_()
    : header()
    , emitter_id()
    , position()
    , direction()
    , range(0.0)
    , strength(0.0)
    , frequency(0.0)
    , modulation()
    , wavelength(0.0)  {
    }
  IrSignal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , emitter_id(_alloc)
    , position(_alloc)
    , direction(_alloc)
    , range(0.0)
    , strength(0.0)
    , frequency(0.0)
    , modulation(_alloc)
    , wavelength(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _emitter_id_type;
  _emitter_id_type emitter_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _direction_type;
  _direction_type direction;

   typedef double _range_type;
  _range_type range;

   typedef double _strength_type;
  _strength_type strength;

   typedef double _frequency_type;
  _frequency_type frequency;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _modulation_type;
  _modulation_type modulation;

   typedef double _wavelength_type;
  _wavelength_type wavelength;





  typedef boost::shared_ptr< ::infrared_msgs::IrSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrared_msgs::IrSignal_<ContainerAllocator> const> ConstPtr;

}; // struct IrSignal_

typedef ::infrared_msgs::IrSignal_<std::allocator<void> > IrSignal;

typedef boost::shared_ptr< ::infrared_msgs::IrSignal > IrSignalPtr;
typedef boost::shared_ptr< ::infrared_msgs::IrSignal const> IrSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrared_msgs::IrSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrared_msgs::IrSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrared_msgs::IrSignal_<ContainerAllocator1> & lhs, const ::infrared_msgs::IrSignal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.emitter_id == rhs.emitter_id &&
    lhs.position == rhs.position &&
    lhs.direction == rhs.direction &&
    lhs.range == rhs.range &&
    lhs.strength == rhs.strength &&
    lhs.frequency == rhs.frequency &&
    lhs.modulation == rhs.modulation &&
    lhs.wavelength == rhs.wavelength;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrared_msgs::IrSignal_<ContainerAllocator1> & lhs, const ::infrared_msgs::IrSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrared_msgs::IrSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrared_msgs::IrSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrared_msgs::IrSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrared_msgs::IrSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrared_msgs::IrSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrared_msgs::IrSignal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrared_msgs::IrSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b33114226fe9c26f156b572ed403903";
  }

  static const char* value(const ::infrared_msgs::IrSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b33114226fe9c26ULL;
  static const uint64_t static_value2 = 0xf156b572ed403903ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrared_msgs::IrSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrared_msgs/IrSignal";
  }

  static const char* value(const ::infrared_msgs::IrSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrared_msgs::IrSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string emitter_id\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 direction\n"
"float64 range\n"
"float64 strength\n"
"float64 frequency\n"
"string modulation\n"
"float64 wavelength\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::infrared_msgs::IrSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrared_msgs::IrSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.emitter_id);
      stream.next(m.position);
      stream.next(m.direction);
      stream.next(m.range);
      stream.next(m.strength);
      stream.next(m.frequency);
      stream.next(m.modulation);
      stream.next(m.wavelength);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IrSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrared_msgs::IrSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrared_msgs::IrSignal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "emitter_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.emitter_id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "strength: ";
    Printer<double>::stream(s, indent + "  ", v.strength);
    s << indent << "frequency: ";
    Printer<double>::stream(s, indent + "  ", v.frequency);
    s << indent << "modulation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.modulation);
    s << indent << "wavelength: ";
    Printer<double>::stream(s, indent + "  ", v.wavelength);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRARED_MSGS_MESSAGE_IRSIGNAL_H
